-- 코드를 입력하세요
SELECT YEAR(A.SALES_DATE) AS YEAR, MONTH(A.SALES_DATE) AS MONTH, COUNT(DISTINCT(A.USER_ID)) AS PURCHASED_USERS,
ROUND(COUNT(DISTINCT A.USER_ID) /
      (SELECT COUNT(USER_ID)
       FROM USER_INFO
       WHERE JOINED LIKE "2021%"), 1) AS PURCHASED_RATIO
FROM ONLINE_SALE AS A
JOIN (SELECT USER_ID
     FROM USER_INFO
     WHERE JOINED LIKE "2021%") AS B
ON A.USER_ID = B.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH